export const FloatingAddButtonActionTypes = {
  SHOW_FLOATING_ADD_BUTTON: "SHOW_FLOATING_ADD_BUTTON",
  HIDE_FLOATING_ADD_BUTTON: "HIDE_FLOATING_ADD_BUTTON",
  CLEAR_FLOATING_ADD_BUTTON: "CLEAR_FLOATING_ADD_BUTTON",
};
